"use client";

import { useState } from "react";
import { ArrowLeft, Beaker, Eye, RotateCcw } from "lucide-react";
import { useRouter } from "next/navigation";
import {
  createLobbyState, declareShow, discardCards, drawFromDeck, drawFromDiscard, endTurn,
  startMatch, startNextHand,
} from "@/lib/yunuf/engine";
import { calculateHandValue, eligibleDiscardDrawIds, highestDeterministicCard, validateDiscard } from "@/lib/yunuf/rules";
import type { Card, Rank, Suit, YunufGameState, YunufPlayer } from "@/lib/yunuf/types";

const ids = ["11111111-1111-4111-8111-111111111111", "22222222-2222-4222-8222-222222222222", "33333333-3333-4333-8333-333333333333"];
const player = (id: string, index: number): YunufPlayer => ({ id, name: ["Rakh", "Arman", "Arhaam"][index], avatar: index, seatIndex: index + 1, hand: [], ready: true, connected: true, eliminated: false, totalScore: 0, roundScore: 0, handsWon: 0, jointWins: 0, showsDeclared: 0, successfulShows: 0, failedShows: 0, revealHandTotalSum: 0, reveals: 0 });
const initial = () => startMatch(createLobbyState(ids.map(player), 100, 30), { random: () => .42, now: Date.now(), id: () => crypto.randomUUID() });
const symbol: Record<Suit, string> = { hearts: "♥", diamonds: "♦", clubs: "♣", spades: "♠" };
const injected = (["Q", "K", "A", "2", "7"] as Rank[]).map((rank, index) => ({ id: `lab-${rank}`, rank, suit: ["hearts", "clubs", "diamonds", "spades", "hearts"][index] as Suit }));

export function YunufDemo() {
  const router = useRouter(); const [state, setState] = useState<YunufGameState>(initial); const [selected, setSelected] = useState<string[]>([]); const [error, setError] = useState<string | null>(null); const current = state.players.find((item) => item.id === state.currentPlayerId); const cards = current?.hand.filter((card) => selected.includes(card.id)) ?? []; const validation = validateDiscard(cards);
  const apply = (action: (state: YunufGameState) => YunufGameState) => { try { setState(action(state)); setSelected([]); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Invalid action"); } };
  const autoTurn = () => apply((game) => { const player = game.players.find((item) => item.id === game.currentPlayerId)!; const highest = highestDeterministicCard(player.hand)!; const discarded = discardCards(game, player.id, [highest.id]); return endTurn(drawFromDeck(discarded, player.id), player.id); });
  const inject = () => setState((game) => ({ ...game, players: game.players.map((item) => item.id === game.currentPlayerId ? { ...item, hand: injected } : item) }));
  const sourceIds = state.drawSourceDiscard ? eligibleDiscardDrawIds(state.drawSourceDiscard.cards, state.drawSourceDiscard.playType) : [];
  return <main className="min-h-dvh bg-[#101614] px-4 py-5 text-[#f8f1dc]"><div className="mx-auto max-w-5xl"><header className="flex items-center justify-between"><button onClick={() => router.push("/games/yunuf")} className="flex min-h-11 items-center gap-2 text-xs font-bold text-white/50"><ArrowLeft size={15}/>Yunuf</button><div className="flex items-center gap-2 text-sm font-black text-[#e8cf8a]"><Beaker size={16}/>RULES LAB</div><button onClick={() => { setState(initial()); setSelected([]); }} className="yunuf-icon-button"><RotateCcw size={14}/></button></header>
    <div className="mt-5 grid gap-3 sm:grid-cols-4"><Stat label="Phase" value={state.status === "playing" || state.status === "finishing_round_after_show" ? state.turnPhase : state.status}/><Stat label="Turn" value={current?.name ?? "Resolved"}/><Stat label="Rounds" value={String(state.completedRounds)}/><Stat label="Show" value={state.showState.active ? "Active" : state.completedRounds >= 3 ? "Unlocked" : "Locked"}/></div>
    <div className="mt-4 flex flex-wrap gap-2"><LabButton onClick={() => setState((game) => ({ ...game, completedRounds: Math.min(3, game.completedRounds + 1) }))}>+ Complete round</LabButton><LabButton onClick={inject}>Inject Q–K–A–2</LabButton><LabButton disabled={!current || state.turnPhase !== "discard"} onClick={autoTurn}>Auto-play turn</LabButton>{state.status === "hand_results" && <LabButton onClick={() => apply(startNextHand)}>Deal next hand</LabButton>}</div>
    {state.showState.active && <div className="show-pulse mt-4 rounded-xl border border-[#d7b45a]/30 bg-[#d7b45a]/10 p-3 text-center text-xs font-black text-[#e8cf8a]">SHOW ACTIVE · resolves after {state.players.find((item) => item.id === state.showState.resolveAfterPlayerId)?.name}</div>}
    <section className="mt-5 grid gap-3 md:grid-cols-3">{state.players.map((player) => <div key={player.id} className={`rounded-2xl border p-4 ${player.id === state.currentPlayerId ? "border-[#d7b45a]/40 bg-[#d7b45a]/[.07]" : "border-white/[.07] bg-white/[.025]"}`}><div className="flex justify-between"><h2 className="text-sm font-black">{player.name}</h2><span className="text-xs font-black text-[#e8cf8a]">{calculateHandValue(player.hand)} pts</span></div><div className="mt-4 flex flex-wrap gap-1.5">{player.hand.map((card) => <button key={card.id} disabled={player.id !== state.currentPlayerId || state.turnPhase !== "discard"} onClick={() => setSelected((items) => items.includes(card.id) ? items.filter((id) => id !== card.id) : [...items, card.id])}><LabCard card={card} selected={selected.includes(card.id)}/></button>)}</div><div className="mt-3 text-[9px] text-white/35">Total score {player.totalScore} · {player.hand.length} cards</div></div>)}</section>
    {error && <div className="mt-4 rounded-lg bg-red-400/10 p-3 text-center text-xs text-red-200">{error}</div>}
    {(state.status === "playing" || state.status === "finishing_round_after_show") && current && <section className="mt-5 rounded-2xl border border-white/[.08] bg-black/20 p-4"><h2 className="text-sm font-black">Current action</h2>{state.turnPhase === "discard" && <><p className={`mt-2 text-xs ${selected.length && validation.valid ? "text-emerald-200" : "text-white/40"}`}>{selected.length ? validation.valid ? `Valid ${validation.playType}: ${validation.orderedCards.map((card) => card.rank).join(" → ")}` : validation.error : "Select cards from the active hand."}</p><LabButton className="mt-3" disabled={!validation.valid} onClick={() => apply((game) => discardCards(game, current.id, selected))}>Discard selection</LabButton></>}{state.turnPhase === "draw" && <div className="mt-3 flex flex-wrap gap-2"><LabButton onClick={() => apply((game) => drawFromDeck(game, current.id))}>Draw from deck</LabButton>{state.drawSourceDiscard?.cards.filter((card) => sourceIds.includes(card.id)).map((card) => <LabButton key={card.id} onClick={() => apply((game) => drawFromDiscard(game, current.id, card.id))}>Take {card.rank}{symbol[card.suit]}</LabButton>)}</div>}{state.turnPhase === "decision" && <div className="mt-3 flex flex-wrap gap-2"><LabButton onClick={() => apply((game) => endTurn(game, current.id))}>End turn</LabButton><LabButton disabled={state.completedRounds < 3 || state.showState.active} onClick={() => apply((game) => declareShow(game, current.id))}><Eye size={13}/>Declare Show</LabButton></div>}</section>}
    {state.result && <section className="mt-5 rounded-2xl border border-[#d7b45a]/25 bg-[#d7b45a]/[.06] p-5"><h2 className="text-lg font-black text-[#e8cf8a]">Hand resolved</h2><pre className="mt-3 overflow-auto text-[10px] leading-5 text-white/55">{JSON.stringify(state.result, null, 2)}</pre></section>}
    <p className="mt-6 text-center text-[9px] text-white/25">Local-only simulation · all hands intentionally visible · no database used</p></div></main>;
}

function LabCard({ card, selected }: { card: Card; selected: boolean }) { const red = card.suit === "hearts" || card.suit === "diamonds"; return <span className={`block h-20 w-14 rounded-md bg-[#faf4df] p-1.5 text-left shadow-lg ${red ? "text-red-700" : "text-[#17201d]"} ${selected ? "-translate-y-2 ring-2 ring-[#d7b45a]" : ""}`}><b>{card.rank}</b><span className="block">{symbol[card.suit]}</span></span>; }
function LabButton({ children, className = "", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`inline-flex min-h-10 items-center justify-center gap-1.5 rounded-lg border border-[#d7b45a]/30 bg-[#d7b45a]/10 px-3 text-[10px] font-black text-[#e8cf8a] disabled:opacity-30 ${className}`} {...props}>{children}</button>; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/[.07] bg-white/[.025] p-3"><div className="text-[8px] font-black uppercase tracking-wider text-white/30">{label}</div><div className="mt-1 text-xs font-black text-[#e8cf8a]">{value}</div></div>; }
